//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patterns.Specifications.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Patterns.Specifications.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have to have an error feed to subscribe to.
        /// </summary>
        internal static string CheckErrorFeedReason {
            get {
                return ResourceManager.GetString("CheckErrorFeedReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REVERSE THIS!.
        /// </summary>
        internal static string MethodCallBackTalk {
            get {
                return ResourceManager.GetString("MethodCallBackTalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO!.
        /// </summary>
        internal static string PropertyReadBackTalk {
            get {
                return ResourceManager.GetString("PropertyReadBackTalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YEAH, RIGHT!.
        /// </summary>
        internal static string PropertyWriteBackTalk {
            get {
                return ResourceManager.GetString("PropertyWriteBackTalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;configuration&gt;
        ///	&lt;configSections&gt;
        ///		&lt;section name=&quot;settings&quot; type=&quot;Patterns.Specifications.Models.Configuration.TestConfigurationSection, _specs&quot;/&gt;
        ///	&lt;/configSections&gt;
        ///	&lt;settings /&gt;
        ///&lt;/configuration&gt;.
        /// </summary>
        internal static string TestConfig1 {
            get {
                return ResourceManager.GetString("TestConfig1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;configuration&gt;
        ///	&lt;configSections&gt;
        ///		&lt;section name=&quot;settings&quot; type=&quot;Patterns.Specifications.Models.Configuration.TestConfigurationSection, _specs&quot;/&gt;
        ///		&lt;sectionGroup name=&quot;test&quot;&gt;
        ///			&lt;section name=&quot;settings&quot; type=&quot;Patterns.Specifications.Models.Configuration.TestConfigurationSection, _specs&quot; /&gt;
        ///		&lt;/sectionGroup&gt;
        ///	&lt;/configSections&gt;
        ///	&lt;settings /&gt;
        ///	&lt;test&gt;
        ///		&lt;settings /&gt;
        ///	&lt;/test&gt;
        ///&lt;/configuration&gt;.
        /// </summary>
        internal static string TestConfig2 {
            get {
                return ResourceManager.GetString("TestConfig2", resourceCulture);
            }
        }
    }
}
