//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patterns.Logging {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LoggingResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoggingResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Patterns.Logging.LoggingResources", typeof(LoggingResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR:	Exception caught during method {0}: {1}.
        /// </summary>
        internal static string ExceptionErrorFormat {
            get {
                return ResourceManager.GetString("ExceptionErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string ILogValueFormatter_NullValue {
            get {
                return ResourceManager.GetString("ILogValueFormatter_NullValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VALUE TOO LARGE TO DISPLAY.
        /// </summary>
        internal static string ILogValueFormatter_ValueTooLarge {
            get {
                return ResourceManager.GetString("ILogValueFormatter_ValueTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INNER EXCEPTION:	{0}.
        /// </summary>
        internal static string InnerExceptionFormat {
            get {
                return ResourceManager.GetString("InnerExceptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEBUG:	Calling {0} with arguments: {1}.
        /// </summary>
        internal static string MethodArgsDebugFormat {
            get {
                return ResourceManager.GetString("MethodArgsDebugFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAILED.
        /// </summary>
        internal static string MethodInfoFail {
            get {
                return ResourceManager.GetString("MethodInfoFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFO:	Method {0}: {1}.
        /// </summary>
        internal static string MethodInfoFormat {
            get {
                return ResourceManager.GetString("MethodInfoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSED.
        /// </summary>
        internal static string MethodInfoPass {
            get {
                return ResourceManager.GetString("MethodInfoPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEBUG:	Returning from {0} with {1}.
        /// </summary>
        internal static string MethodReturnDebugFormat {
            get {
                return ResourceManager.GetString("MethodReturnDebugFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRACE:	{0}: METHOD START ({1}).
        /// </summary>
        internal static string MethodStartTraceFormat {
            get {
                return ResourceManager.GetString("MethodStartTraceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRACE:	{0}: METHOD STOP ({1}).
        /// </summary>
        internal static string MethodStopTraceFormat {
            get {
                return ResourceManager.GetString("MethodStopTraceFormat", resourceCulture);
            }
        }
    }
}
