//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patterns.Specifications.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Patterns.Specifications.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I expected the count for call requests to go up by {0}.
        /// </summary>
        internal static string CheckCallRequestCountReasonFormat {
            get {
                return ResourceManager.GetString("CheckCallRequestCountReasonFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I expected the count for call responses to go up by {0}.
        /// </summary>
        internal static string CheckCallResponseCountReasonFormat {
            get {
                return ResourceManager.GetString("CheckCallResponseCountReasonFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the collection should still be uninitialized.
        /// </summary>
        internal static string CheckCollectionIsNullReason {
            get {
                return ResourceManager.GetString("CheckCollectionIsNullReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to there shouldn&apos;t be a result when the method threw an exception.
        /// </summary>
        internal static string CheckEmptyCallResultReason {
            get {
                return ResourceManager.GetString("CheckEmptyCallResultReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I expected the count for errors to go up by {0}.
        /// </summary>
        internal static string CheckErrorCountReasonFormat {
            get {
                return ResourceManager.GetString("CheckErrorCountReasonFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have to have an error feed to subscribe to.
        /// </summary>
        internal static string CheckErrorFeedReason {
            get {
                return ResourceManager.GetString("CheckErrorFeedReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the property read should have failed, resulting in the default property type.
        /// </summary>
        internal static string CheckPropertyReadResultIsDefaultReason {
            get {
                return ResourceManager.GetString("CheckPropertyReadResultIsDefaultReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if the property read succeeded, then I should have gotten the value I expected.
        /// </summary>
        internal static string CheckPropertyReadResultReason {
            get {
                return ResourceManager.GetString("CheckPropertyReadResultReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if the propert write succeeded, I should have gotten the value I expected.
        /// </summary>
        internal static string CheckPropertyWriteResultReason {
            get {
                return ResourceManager.GetString("CheckPropertyWriteResultReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I expected the count for read requests to go up by {0}.
        /// </summary>
        internal static string CheckReadRequestCountReasonFormat {
            get {
                return ResourceManager.GetString("CheckReadRequestCountReasonFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I expected the count for read responses to go up by {0}.
        /// </summary>
        internal static string CheckReadResponseCountReasonFormat {
            get {
                return ResourceManager.GetString("CheckReadResponseCountReasonFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if the method completed with no errors, I should have a valid return value.
        /// </summary>
        internal static string CheckValidCallResultReason {
            get {
                return ResourceManager.GetString("CheckValidCallResultReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I expected the count for write requests to go up by {0}.
        /// </summary>
        internal static string CheckWriteRequestCountReasonFormat {
            get {
                return ResourceManager.GetString("CheckWriteRequestCountReasonFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the previous step was supposed to catch one of these.
        /// </summary>
        internal static string ExpectedExceptionFromLastStepReason {
            get {
                return ResourceManager.GetString("ExpectedExceptionFromLastStepReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the exception from the previous step was supposed to be for {0}.
        /// </summary>
        internal static string LastStepErrorArgumentFormat {
            get {
                return ResourceManager.GetString("LastStepErrorArgumentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REVERSE THIS!.
        /// </summary>
        internal static string MethodCallBackTalk {
            get {
                return ResourceManager.GetString("MethodCallBackTalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO!.
        /// </summary>
        internal static string PropertyReadBackTalk {
            get {
                return ResourceManager.GetString("PropertyReadBackTalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YEAH, RIGHT!.
        /// </summary>
        internal static string PropertyWriteBackTalk {
            get {
                return ResourceManager.GetString("PropertyWriteBackTalk", resourceCulture);
            }
        }
    }
}
