//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patterns.Specifications.Models.Collections {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CollectionModelResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CollectionModelResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Patterns.Specifications.Models.Collections.CollectionModelResources", typeof(CollectionModelResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I expected all the strings to be non-null.
        /// </summary>
        internal static string AssertResultStringSetAllNonNull_Reason {
            get {
                return ResourceManager.GetString("AssertResultStringSetAllNonNull_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I expected the set of strings to be empty.
        /// </summary>
        internal static string AssertResultStringSetEmpty_Reason {
            get {
                return ResourceManager.GetString("AssertResultStringSetEmpty_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I expected the set of strings to be non-empty.
        /// </summary>
        internal static string AssertResultStringSetNonEmpty_Reason {
            get {
                return ResourceManager.GetString("AssertResultStringSetNonEmpty_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I expected the set of strings to be non-null.
        /// </summary>
        internal static string AssertResultStringSetNonNull_Reason {
            get {
                return ResourceManager.GetString("AssertResultStringSetNonNull_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A default factory has not been chosen for the {0} type..
        /// </summary>
        internal static string DefaultFactoryNotFound {
            get {
                return ResourceManager.GetString("DefaultFactoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Strings.
        /// </summary>
        internal static string OriginalStringsLabel {
            get {
                return ResourceManager.GetString("OriginalStringsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result Strings.
        /// </summary>
        internal static string ResultStringsLabel {
            get {
                return ResourceManager.GetString("ResultStringsLabel", resourceCulture);
            }
        }
    }
}
